### ISSUE TITLE
Dynamic steps

### ISSUE THREAD

**Issue by george-i** [eberlitz/material-steppers#10]
In my scenario, the user should see a step if checks a radio button.
Is this possible?

**Comment by eberlitz** [comment]
I'm using this component with dynamic steps by using an ngRepeat. In my scneario I add and remove steps.

```
<md-stepper flex id="stepper-rematricula" md-mobile-step-text md-linear md-alternative>
        <md-step md-label="{{::step.desc}}" ng-repeat="step in ::$ctrl.steps">
```
