### ISSUE TITLE
Doesn't work with Angular 1.4.9

### ISSUE THREAD

**Issue by pmullot** [eberlitz/material-steppers#13]
Hi, 

Congratulations for the great work.
Just want to suggest to include a minimum version of angular in READ.ME to avoid problems
I've been chasing ghosts during several hours to find out that steppers would work on 1.4.9

Thanks

**Comment by eberlitz** [comment]
Hi thanks for the info. I updated the readme

**Comment by WeHateNick** [comment]
@eberlitz Does this mean this component does _not_ work for angular 1.5+ apps?

**Comment by anukiransolur** [comment]
@eberlitz The lib breaks on 1.4.9 but the note says it works. Pretty confusing.
