### ISSUE TITLE
Input inside stepper

### ISSUE THREAD

**Issue by mthomasson** [eberlitz/material-steppers#17]
Hi,

I try to put an input inside a stepper, but I can't link the ng-model in my controller. And you don't seem to link it to somethng in the demo. Does it work? And if yes, how do we access it?

Thxs!

**Comment by eberlitz** [comment]
Yes. it works. You should not need to do anything special for this, as the component uses transclusion.

**Comment by mthomasson** [comment]
Ok, then why in the demo, when you press back from the third step and you had filled something in the second before, the input is empty again?

**Comment by eberlitz** [comment]
Because only the visible step is rendered in the HTML. The component uses ng-if to show/hide the active step. So if you want to preserve state, you should bind the input to an property that exists even if the step is not showing.

**Comment by mthomasson** [comment]
Ok thxs for your so quick answers!

**Comment by eberlitz** [comment]
I've just updated the demo page (https://eberlitz.github.io/material-steppers/demo/)
To show how to do it.

Try to press back from the third step after you had filled something in the second before, the input should now be filled in.
