### ISSUE TITLE
update bower

### ISSUE THREAD

**Issue by mangrish** [eberlitz/material-steppers#2]
Still playing with the project. You're missing a dependency in bower. Currently solved with overrides:

```
 "material-steppers": {
      "main": [
          "dist/material-steppers.min.js",
          "dist/material-steppers.css"
      ]
    }
```

Ideally the non minified versions would be better but when i try using the non minified version it looks for another tpl file.

**Comment by eberlitz** [comment]
Hi, I fix this issue and you can get it with the new version 1.0.2. Thanks for the feedback.
