### ISSUE TITLE
Keep the proper mdl-stepper reference

### ISSUE THREAD

**Issue by axdemelas** [eberlitz/material-steppers#6]
Hi,

Congrats for doing a good job here.

Angular support is [a feature request](https://github.com/ahlechandre/mdl-stepper/issues/25) on our mdl-stepper project. 

Is visible that in some parts material-steppers is inspired on mdl-stepper and this is a really nice thing. What bothers me is that also some parts of your repository is like a copy and paste without proper reference to the original author. Something like:
### MDL-Stepper

![method-table-2](https://cloud.githubusercontent.com/assets/7119058/19367990/38a761bc-9174-11e6-9c06-2446f0320c48.jpg)
### material-steppers

![method-table](https://cloud.githubusercontent.com/assets/7119058/19367989/389ed63c-9174-11e6-8fe6-f04d2496b6bc.jpg)

The [react-mdl-stepper](https://github.com/adamdawkins/react-mdl-stepper) is a project example that was inspired by the mdl-stepper and quoted us in his README.md.

You can give the reference of mdl-stepper?

Thanks.

**Comment by ghost** [comment]
+1

**Comment by eberlitz** [comment]
README updated
